### ISSUE TITLE
Add the Semaphore Explorer app

### ISSUE THREAD

**Issue by vplasencia** [semaphore-protocol/extensions#1]
## Description

The idea is to add the Semaphore explorer to the extensions repo.

## Tasks

- [x] Add the new Semaphore explorer to the extensions repo.
- [x] Improve UX of the new explorer.
- [x] Update explorer domain to point to the new explorer.
- [x] Archive the old explorer.
